const mongoose = require('mongoose');

const Schema = mongoose.Schema;

const LanguagesSchema = new Schema({
  JavaScript: { type: Number, default: 0 },
  Python: { type: Number, default: 0 },
  HTML: { type: Number, default: 0 },
  CSS: { type: Number, default: 0 },
  Shell: { type: Number, default: 0 },
  GLSL: { type: Number, default: 0 },
  Ruby: { type: Number, default: 0 },
  ActionScript: { type: Number, default: 0 },
  'C++': { type: Number, default: 0 },
  C: { type: Number, default: 0 },
  Makefile: { type: Number, default: 0 },
  TypeScript: { type: Number, default: 0 },
  Dart: { type: Number, default: 0 },
  'Protocol Buffer': { type: Number, default: 0 },
  Java: { type: Number, default: 0 },
  LiveScript: { type: Number, default: 0 },
  Gosu: { type: Number, default: 0 },
  CoffeeScript: { type: Number, default: 0 },
  PHP: { type: Number, default: 0 },
  Groovy: { type: Number, default: 0 },
  'Objective-C': { type: Number, default: 0 },
  Perl: { type: Number, default: 0 },
  'Vim script': { type: Number, default: 0 },
  Haskell: { type: Number, default: 0 },
  Go: { type: Number, default: 0 },
  AppleScript: { type: Number, default: 0 },
  Batchfile: { type: Number, default: 0 },
  Processing: { type: Number, default: 0 },
  ApacheConf: { type: Number, default: 0 },
  Lua: { type: Number, default: 0 },
  Groff: { type: Number, default: 0 },
  PostScript: { type: Number, default: 0 },
  'Visual Basic': { type: Number, default: 0 },
  D: { type: Number, default: 0 },
  Matlab: { type: Number, default: 0 },
  Assembly: { type: Number, default: 0 },
  Vue: { type: Number, default: 0 },
  Nginx: { type: Number, default: 0 },
  Swift: { type: Number, default: 0 },
  PLpgSQL: { type: Number, default: 0 },
  Dockerfile: { type: Number, default: 0 },
  Nix: { type: Number, default: 0 },
  Elm: { type: Number, default: 0 },
  Clojure: { type: Number, default: 0 },
  SQLPL: { type: Number, default: 0 },
  PowerShell: { type: Number, default: 0 },
  Smarty: { type: Number, default: 0 },
  Gherkin: { type: Number, default: 0 },
  Rust: { type: Number, default: 0 },
  CMake: { type: Number, default: 0 },
  Scala: { type: Number, default: 0 },
  Handlebars: { type: Number, default: 0 },
  'C#': { type: Number, default: 0 },
  'F#': { type: Number, default: 0 },
  OCaml: { type: Number, default: 0 },
  HLSL: { type: Number, default: 0 },
  ShaderLab: { type: Number, default: 0 },
  ANTLR: { type: Number, default: 0 },
  Kotlin: { type: Number, default: 0 },
  ASP: { type: Number, default: 0 },
  'Objective-C++': { type: Number, default: 0 },
  Roff: { type: Number, default: 0 },
  NSIS: { type: Number, default: 0 },
  M4: { type: Number, default: 0 },
  GDB: { type: Number, default: 0 },
  Harbour: { type: Number, default: 0 },
  Tcl: { type: Number, default: 0 },
  Scheme: { type: Number, default: 0 },
  OpenSCAD: { type: Number, default: 0 },
  'DCPU-16 ASM': { type: Number, default: 0 },
  TeX: { type: Number, default: 0 },
  R: { type: Number, default: 0 },
  Coq: { type: Number, default: 0 },
  'Emacs Lisp': { type: Number, default: 0 },
  Fortran: { type: Number, default: 0 },
  PLSQL: { type: Number, default: 0 },
  'Csound Document': { type: Number, default: 0 },
  'Grammatical Framework': { type: Number, default: 0 },
  Bison: { type: Number, default: 0 },
  Logos: { type: Number, default: 0 },
  Prolog: { type: Number, default: 0 },
  Erlang: { type: Number, default: 0 },
  IDL: { type: Number, default: 0 },
  Awk: { type: Number, default: 0 },
  Thrift: { type: Number, default: 0 },
  FreeMarker: { type: Number, default: 0 },
  'Jupyter Notebook': { type: Number, default: 0 },
  HCL: { type: Number, default: 0 },
  Lex: { type: Number, default: 0 },
  Smalltalk: { type: Number, default: 0 },
  Yacc: { type: Number, default: 0 },
  Arduino: { type: Number, default: 0 },
  DTrace: { type: Number, default: 0 },
  Cuda: { type: Number, default: 0 },
  PAWN: { type: Number, default: 0 },
  XSLT: { type: Number, default: 0 },
  SourcePawn: { type: Number, default: 0 },
  'Common Lisp': { type: Number, default: 0 },
  'Perl 6': { type: Number, default: 0 },
  ABAP: { type: Number, default: 0 },
  PigLatin: { type: Number, default: 0 },
  'AGS Script': { type: Number, default: 0 },
  GAP: { type: Number, default: 0 },
  'GCC Machine Description': { type: Number, default: 0 },
  UnrealScript: { type: Number, default: 0 },
  XS: { type: Number, default: 0 },
  sed: { type: Number, default: 0 },
  BitBake: { type: Number, default: 0 },
  Pascal: { type: Number, default: 0 },
  BlitzBasic: { type: Number, default: 0 },
  'DIGITAL Command Language': { type: Number, default: 0 },
  eC: { type: Number, default: 0 },
  Scilab: { type: Number, default: 0 },
  'POV-Ray SDL': { type: Number, default: 0 },
  AngelScript: { type: Number, default: 0 },
  Julia: { type: Number, default: 0 },
  Terra: { type: Number, default: 0 },
  'Standard ML': { type: Number, default: 0 },
  VCL: { type: Number, default: 0 },
  XML: { type: Number, default: 0 },
  M: { type: Number, default: 0 },
  Hack: { type: Number, default: 0 },
  'OpenEdge ABL': { type: Number, default: 0 },
  Haxe: { type: Number, default: 0 },
  Mako: { type: Number, default: 0 },
  xBase: { type: Number, default: 0 },
  Agda: { type: Number, default: 0 },
  Brainfuck: { type: Number, default: 0 },
  Gnuplot: { type: Number, default: 0 },
  Zimpl: { type: Number, default: 0 },
  Io: { type: Number, default: 0 },
  'Ren\'Py': { type: Number, default: 0 },
  MoonScript: { type: Number, default: 0 },
  Elixir: { type: Number, default: 0 },
  'Objective-J': { type: Number, default: 0 },
  Racket: { type: Number, default: 0 },
  timestamp: { type: Date, default: new Date() },
});
const AFRICA = mongoose.model('AFRICA', LanguagesSchema);
const BRAZIL = mongoose.model('BRAZIL', LanguagesSchema);
const CHINA = mongoose.model('CHINA', LanguagesSchema);
const INDIA = mongoose.model('INDIA', LanguagesSchema);
const JAPAN = mongoose.model('JAPAN', LanguagesSchema);
const RUSSIA = mongoose.model('RUSSIA', LanguagesSchema);
const SWEDEN = mongoose.model('SWEDEN', LanguagesSchema);
const SWITZERLAND = mongoose.model('SWITZERLAND', LanguagesSchema);
const USA = mongoose.model('USA', LanguagesSchema);
module.exports = {
  AFRICA,
  BRAZIL,
  CHINA,
  INDIA,
  JAPAN,
  RUSSIA,
  SWEDEN,
  SWITZERLAND,
  USA,
};
